version: "3.8"

services:
  app:
    image: roundrobin/gastrolytics-web:latest
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - ATLAS_MONGODB_URI=${ATLAS_MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ${UPLOADS_PATH}:/app/public/uploads

  nginx:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the custom Nginx config
      - ./certbot/conf:/etc/letsencrypt                          
      - ./certbot/www:/var/www/certbot  
    restart: unless-stopped

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: renew --webroot -w /var/www/certbot --quiet  
