version: "3.8"

services:
  app:
    image: roundrobin/gastrolytics-web:0.1.0
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - ATLAS_MONGODB_URI=${ATLAS_MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ${UPLOADS_PATH}:/app/public/uploads

  nginx:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"   # Expose Nginx on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the custom Nginx config
    restart: unless-stopped
